/**
  * TelstraSMSMessagingAPILib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';
angular.module('TelstraSMSMessagingAPILib')
    .factory('ModelFactory', ['SendSMSRequest',
        'MessageSentResponse',
        'InboundPollResponse',
        'OutboundPollResponse',
        ModelFactory]);

	/**
	 * Factory service to create instances of models and exception classes
	 */
    function ModelFactory(SendSMSRequest, MessageSentResponse, InboundPollResponse, OutboundPollResponse) {

		var classMap = {
            SendSMSRequest: SendSMSRequest,
            MessageSentResponse: MessageSentResponse,
            InboundPollResponse: InboundPollResponse,
            OutboundPollResponse: OutboundPollResponse
		};

		return {
		    /**
		     * Creates instance of a model class
		     * @param  modelName  {string}  Name of class to instantiate
		     * @returns  {object} Instance of the model class
		     */
			getInstance: function(modelName) {
        		return new classMap[modelName]();
			}
		};
	}

}(angular));
