/**
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';


const Configuration = {
    // The base Uri for API calls
    BASEURI: 'https://sapi.telstra.com/v2',

};

module.exports = Configuration;
