/**
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const SendSMSRequest = require('../lib/Models/SendSMSRequest');
const MessageSentResponse = require('../lib/Models/MessageSentResponse');
const InboundPollResponse = require('../lib/Models/InboundPollResponse');
const OutboundPollResponse = require('../lib/Models/OutboundPollResponse');
const ErrorErrorException = require('../lib/Exceptions/ErrorErrorException');

const classMap = {
    SendSMSRequest,
    MessageSentResponse,
    InboundPollResponse,
    OutboundPollResponse,
    ErrorErrorException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
