/*
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.sapi;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://sapi.telstra.com/v2";

}
