/*
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.telstra.sapi;

import com.telstra.sapi.controllers.*;
import com.telstra.sapi.http.client.HttpClient;

public class TelstraSMSMessagingAPIClient {
    /**
     * Singleton access to SMS controller
     * @return	Returns the SMSController instance 
     */
    public SMSController getSMS() {
        return SMSController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public TelstraSMSMessagingAPIClient() {
    }

}