/**
  * TelstraSMSMessagingAPILib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('TelstraSMSMessagingAPILib')
    .factory('MessageTypeEnum', [MessageTypeEnumModel]);

    function MessageTypeEnumModel() {
        return {
            //TODO: Write general description for this element
            SMS: 'SMS',
    
            //TODO: Write general description for this element
            MMS: 'MMS',
    
            //TODO: Write general description for this element
            RCS: 'RCS'
        };
    }

}(angular));
