/**
 * TelstraSMSMessagingAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of OutboundPollResponse
 *
 * @constructor
 */
angular.module('TelstraSMSMessagingAPILib')
    .factory('OutboundPollResponse', ['BaseModel', OutboundPollResponseModel]);

    function OutboundPollResponseModel(BaseModel) {
        var OutboundPollResponse = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.to = this.getValue(obj.to);
            this.receivedTimestamp = this.getValue(obj.receivedTimestamp);
            this.sentTimestamp = this.getValue(obj.sentTimestamp);
            this.status = this.getValue(obj.status);
        };

        OutboundPollResponse.prototype = new BaseModel();
        OutboundPollResponse.prototype.constructor = OutboundPollResponse;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        OutboundPollResponse.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'to', realName: 'to' },
                { name: 'receivedTimestamp', realName: 'receivedTimestamp' },
                { name: 'sentTimestamp', realName: 'sentTimestamp' },
                { name: 'status', realName: 'status' }
            ]);
        };
    
        /**
         * The phone number (recipient) the message was sent to (in E.164 format).
         *
         * @return {string|null}
         */
        OutboundPollResponse.prototype.getTo = function () {
            return this.to;
        };
    
        /**
         * Setter for To
         * 
         * @param {string|null} value 
         */
        OutboundPollResponse.prototype.setTo = function (value) {
            this.to = value;
        };
    
        /**
         * The date and time when the message was recieved by recipient.
         *
         * @return {string|null}
         */
        OutboundPollResponse.prototype.getReceivedTimestamp = function () {
            return this.receivedTimestamp;
        };
    
        /**
         * Setter for ReceivedTimestamp
         * 
         * @param {string|null} value 
         */
        OutboundPollResponse.prototype.setReceivedTimestamp = function (value) {
            this.receivedTimestamp = value;
        };
    
        /**
         * The date and time when the message was sent.
         *
         * @return {string|null}
         */
        OutboundPollResponse.prototype.getSentTimestamp = function () {
            return this.sentTimestamp;
        };
    
        /**
         * Setter for SentTimestamp
         * 
         * @param {string|null} value 
         */
        OutboundPollResponse.prototype.setSentTimestamp = function (value) {
            this.sentTimestamp = value;
        };
    
        /**
         * Delivery status of the message
         *
         * @return {StatusEnum|null}
         */
        OutboundPollResponse.prototype.getStatus = function () {
            return this.status;
        };
    
        /**
         * Setter for Status
         * 
         * @param {StatusEnum|null} value 
         */
        OutboundPollResponse.prototype.setStatus = function (value) {
            this.status = value;
        };
    
        return OutboundPollResponse;
    }

}(angular));
