/**
  * TelstraSMSMessagingAPILib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('TelstraSMSMessagingAPILib')
    .factory('StatusEnum', [StatusEnumModel]);

    function StatusEnumModel() {
        return {
            //TODO: Write general description for this element
            PEND: 'PEND',
    
            //TODO: Write general description for this element
            SENT: 'SENT',
    
            //TODO: Write general description for this element
            DELIVRD: 'DELIVRD',
    
            //TODO: Write general description for this element
            EXPIRED: 'EXPIRED',
    
            //TODO: Write general description for this element
            DELETED: 'DELETED',
    
            //TODO: Write general description for this element
            UNDVBL: 'UNDVBL',
    
            //TODO: Write general description for this element
            REJECTED: 'REJECTED',
    
            //TODO: Write general description for this element
            READ: 'READ'
        };
    }

}(angular));
